//
//  BBDirectoryResponder.m
//  Blackbox
//
//  Created by Matt Patenaude on 12/8/08.
//  Copyright 2008 Matt Patenaude. All rights reserved.
//

#import "BBDirectoryResponder.h"
#import "BBRequest.h"
#import "MPTidbits.h"


@implementation BBDirectoryResponder

#pragma mark Initializers
- (id)init
{
	NSString *publicDirectory = [NSHomeDirectory() stringByAppendingPathComponent:@"Public"];
	
	return [self initWithDirectory:publicDirectory];
}
- (id)initWithDirectory:(NSString *)pathToDirectory
{
	if (self = [super init])
	{
		BOOL isDir;
		if (pathToDirectory == nil || (![[NSFileManager defaultManager] fileExistsAtPath:pathToDirectory isDirectory:&isDir] || !isDir))
		{
			[self release];
			return nil;
		}
		
		directoryPath = [pathToDirectory copy];
		allowDirectoryListing = YES;
	}
	return self;
}
+ (id)directoryResponderWithDirectory:(NSString *)pathToDirectory
{
	return [[[self alloc] initWithDirectory:pathToDirectory] autorelease];
}

#pragma mark Deallocator
- (void)dealloc
{
	if (directoryPath != nil)
		[directoryPath release];
	[super dealloc];
}

#pragma mark Properties
- (BOOL)allowDirectoryListing
{
	return allowDirectoryListing;
}
- (void)setAllowDirectoryListing:(BOOL)shouldAllow
{
	allowDirectoryListing = shouldAllow;
}

#pragma mark Methods
- (void)handleRequest:(BBRequest *)theRequest
{
	static NSDictionary *supportedTypes = nil;
	
	if (supportedTypes == nil)
	{
		// created from Apache default MIME types
		supportedTypes = [[NSDictionary alloc] initWithObjectsAndKeys:
										  @"application/andrew-inset", @"ez",
										  @"application/atom+xml", @"atom",
										  @"application/atomcat+xml", @"atomcat",
										  @"application/atomsvc+xml", @"atomsvc",
										  @"application/ccxml+xml", @"ccxml",
										  @"application/davmount+xml", @"davmount",
										  @"application/ecmascript", @"ecma",
										  @"application/font-tdpfr", @"pfr",
										  @"application/hyperstudio", @"stk",
										  @"application/javascript", @"js",
										  @"application/json", @"json",
										  @"application/mac-binhex40", @"hqx",
										  @"application/mac-compactpro", @"cpt",
										  @"application/marc", @"mrc",
										  @"application/mathematica", @"ma",
										  @"application/mathematica", @"nb",
										  @"application/mathematica", @"mb",
										  @"application/mathml+xml", @"mathml",
										  @"application/mbox", @"mbox",
										  @"application/mediaservercontrol+xml", @"mscml",
										  @"application/mp4", @"mp4s",
										  @"application/msword", @"doc",
										  @"application/msword", @"dot",
										  @"application/mxf", @"mxf",
										  @"application/octet-stream", @"bin",
										  @"application/octet-stream", @"dms",
										  @"application/octet-stream", @"lha",
										  @"application/octet-stream", @"lzh",
										  @"application/octet-stream", @"class",
										  @"application/octet-stream", @"so",
										  @"application/octet-stream", @"iso",
										  @"application/octet-stream", @"dmg",
										  @"application/octet-stream", @"dist",
										  @"application/octet-stream", @"distz",
										  @"application/octet-stream", @"pkg",
										  @"application/octet-stream", @"bpk",
										  @"application/octet-stream", @"dump",
										  @"application/octet-stream", @"elc",
										  @"application/octet-stream", @"scpt",
										  @"application/oda", @"oda",
										  @"application/ogg", @"ogg",
										  @"application/pdf", @"pdf",
										  @"application/pgp-encrypted", @"pgp",
										  @"application/pgp-signature", @"asc",
										  @"application/pgp-signature", @"sig",
										  @"application/pics-rules", @"prf",
										  @"application/pkcs10", @"p10",
										  @"application/pkcs7-mime", @"p7m",
										  @"application/pkcs7-mime", @"p7c",
										  @"application/pkcs7-signature", @"p7s",
										  @"application/pkix-cert", @"cer",
										  @"application/pkix-crl", @"crl",
										  @"application/pkix-pkipath", @"pkipath",
										  @"application/pkixcmp", @"pki",
										  @"application/pls+xml", @"pls",
										  @"application/postscript", @"ai",
										  @"application/postscript", @"eps",
										  @"application/postscript", @"ps",
										  @"application/prs.cww", @"cww",
										  @"application/rdf+xml", @"rdf",
										  @"application/reginfo+xml", @"rif",
										  @"application/relax-ng-compact-syntax", @"rnc",
										  @"application/resource-lists+xml", @"rl",
										  @"application/rls-services+xml", @"rs",
										  @"application/rsd+xml", @"rsd",
										  @"application/rss+xml", @"rss",
										  @"application/rtf", @"rtf",
										  @"application/sbml+xml", @"sbml",
										  @"application/sdp", @"sdp",
										  @"application/set-payment-initiation", @"setpay",
										  @"application/set-registration-initiation", @"setreg",
										  @"application/shf+xml", @"shf",
										  @"application/smil+xml", @"smi",
										  @"application/smil+xml", @"smil",
										  @"application/srgs", @"gram",
										  @"application/srgs+xml", @"grxml",
										  @"application/ssml+xml", @"ssml",
										  @"application/vnd.3gpp.pic-bw-large", @"plb",
										  @"application/vnd.3gpp.pic-bw-small", @"psb",
										  @"application/vnd.3gpp.pic-bw-var", @"pvb",
										  @"application/vnd.3m.post-it-notes", @"pwn",
										  @"application/vnd.accpac.simply.aso", @"aso",
										  @"application/vnd.accpac.simply.imp", @"imp",
										  @"application/vnd.acucobol", @"acu",
										  @"application/vnd.acucorp", @"atc",
										  @"application/vnd.acucorp", @"acutc",
										  @"application/vnd.adobe.xdp+xml", @"xdp",
										  @"application/vnd.adobe.xfdf", @"xfdf",
										  @"application/vnd.amiga.ami", @"ami",
										  @"application/vnd.anser-web-certificate-issue-initiation", @"cii",
										  @"application/vnd.anser-web-funds-transfer-initiation", @"fti",
										  @"application/vnd.antix.game-component", @"atx",
										  @"application/vnd.apple.installer+xml", @"mpkg",
										  @"application/vnd.audiograph", @"aep",
										  @"application/vnd.blueice.multipass", @"mpm",
										  @"application/vnd.bmi", @"bmi",
										  @"application/vnd.businessobjects", @"rep",
										  @"application/vnd.chemdraw+xml", @"cdxml",
										  @"application/vnd.chipnuts.karaoke-mmd", @"mmd",
										  @"application/vnd.cinderella", @"cdy",
										  @"application/vnd.claymore", @"cla",
										  @"application/vnd.clonk.c4group", @"c4g",
										  @"application/vnd.clonk.c4group", @"c4d",
										  @"application/vnd.clonk.c4group", @"c4f",
										  @"application/vnd.clonk.c4group", @"c4p",
										  @"application/vnd.clonk.c4group", @"c4u",
										  @"application/vnd.commonspace", @"csp",
										  @"application/vnd.commonspace", @"cst",
										  @"application/vnd.contact.cmsg", @"cdbcmsg",
										  @"application/vnd.cosmocaller", @"cmc",
										  @"application/vnd.crick.clicker", @"clkx",
										  @"application/vnd.crick.clicker.keyboard", @"clkk",
										  @"application/vnd.crick.clicker.palette", @"clkp",
										  @"application/vnd.crick.clicker.template", @"clkt",
										  @"application/vnd.crick.clicker.wordbank", @"clkw",
										  @"application/vnd.criticaltools.wbs+xml", @"wbs",
										  @"application/vnd.ctc-posml", @"pml",
										  @"application/vnd.cups-ppd", @"ppd",
										  @"application/vnd.curl", @"curl",
										  @"application/vnd.data-vision.rdz", @"rdz",
										  @"application/vnd.denovo.fcselayout-link", @"fe_launch",
										  @"application/vnd.dna", @"dna",
										  @"application/vnd.dolby.mlp", @"mlp",
										  @"application/vnd.dpgraph", @"dpg",
										  @"application/vnd.dreamfactory", @"dfac",
										  @"application/vnd.ecowin.chart", @"mag",
										  @"application/vnd.enliven", @"nml",
										  @"application/vnd.epson.esf", @"esf",
										  @"application/vnd.epson.msf", @"msf",
										  @"application/vnd.epson.quickanime", @"qam",
										  @"application/vnd.epson.salt", @"slt",
										  @"application/vnd.epson.ssf", @"ssf",
										  @"application/vnd.eszigno3+xml", @"es3",
										  @"application/vnd.eszigno3+xml", @"et3",
										  @"application/vnd.ezpix-album", @"ez2",
										  @"application/vnd.ezpix-package", @"ez3",
										  @"application/vnd.fdf", @"fdf",
										  @"application/vnd.flographit", @"gph",
										  @"application/vnd.fluxtime.clip", @"ftc",
										  @"application/vnd.framemaker", @"fm",
										  @"application/vnd.framemaker", @"frame",
										  @"application/vnd.framemaker", @"maker",
										  @"application/vnd.frogans.fnc", @"fnc",
										  @"application/vnd.frogans.ltf", @"ltf",
										  @"application/vnd.fsc.weblaunch", @"fsc",
										  @"application/vnd.fujitsu.oasys", @"oas",
										  @"application/vnd.fujitsu.oasys2", @"oa2",
										  @"application/vnd.fujitsu.oasys3", @"oa3",
										  @"application/vnd.fujitsu.oasysgp", @"fg5",
										  @"application/vnd.fujitsu.oasysprs", @"bh2",
										  @"application/vnd.fujixerox.ddd", @"ddd",
										  @"application/vnd.fujixerox.docuworks", @"xdw",
										  @"application/vnd.fujixerox.docuworks.binder", @"xbd",
										  @"application/vnd.fuzzysheet", @"fzs",
										  @"application/vnd.genomatix.tuxedo", @"txd",
										  @"application/vnd.google-earth.kml+xml", @"kml",
										  @"application/vnd.google-earth.kmz", @"kmz",
										  @"application/vnd.grafeq", @"gqf",
										  @"application/vnd.grafeq", @"gqs",
										  @"application/vnd.groove-account", @"gac",
										  @"application/vnd.groove-help", @"ghf",
										  @"application/vnd.groove-identity-message", @"gim",
										  @"application/vnd.groove-injector", @"grv",
										  @"application/vnd.groove-tool-message", @"gtm",
										  @"application/vnd.groove-tool-template", @"tpl",
										  @"application/vnd.groove-vcard", @"vcg",
										  @"application/vnd.handheld-entertainment+xml", @"zmm",
										  @"application/vnd.hbci", @"hbci",
										  @"application/vnd.hhe.lesson-player", @"les",
										  @"application/vnd.hp-hpgl", @"hpgl",
										  @"application/vnd.hp-hpid", @"hpid",
										  @"application/vnd.hp-hps", @"hps",
										  @"application/vnd.hp-jlyt", @"jlt",
										  @"application/vnd.hp-pcl", @"pcl",
										  @"application/vnd.hp-pclxl", @"pclxl",
										  @"application/vnd.hzn-3d-crossword", @"x3d",
										  @"application/vnd.ibm.minipay", @"mpy",
										  @"application/vnd.ibm.modcap", @"afp",
										  @"application/vnd.ibm.modcap", @"listafp",
										  @"application/vnd.ibm.modcap", @"list3820",
										  @"application/vnd.ibm.rights-management", @"irm",
										  @"application/vnd.ibm.secure-container", @"sc",
										  @"application/vnd.igloader", @"igl",
										  @"application/vnd.immervision-ivp", @"ivp",
										  @"application/vnd.immervision-ivu", @"ivu",
										  @"application/vnd.intercon.formnet", @"xpw",
										  @"application/vnd.intercon.formnet", @"xpx",
										  @"application/vnd.intu.qbo", @"qbo",
										  @"application/vnd.intu.qfx", @"qfx",
										  @"application/vnd.ipunplugged.rcprofile", @"rcprofile",
										  @"application/vnd.irepository.package+xml", @"irp",
										  @"application/vnd.is-xpr", @"xpr",
										  @"application/vnd.jam", @"jam",
										  @"application/vnd.jcp.javame.midlet-rms", @"rms",
										  @"application/vnd.jisp", @"jisp",
										  @"application/vnd.kahootz", @"ktz",
										  @"application/vnd.kahootz", @"ktr",
										  @"application/vnd.kde.karbon", @"karbon",
										  @"application/vnd.kde.kchart", @"chrt",
										  @"application/vnd.kde.kformula", @"kfo",
										  @"application/vnd.kde.kivio", @"flw",
										  @"application/vnd.kde.kontour", @"kon",
										  @"application/vnd.kde.kpresenter", @"kpr",
										  @"application/vnd.kde.kpresenter", @"kpt",
										  @"application/vnd.kde.kspread", @"ksp",
										  @"application/vnd.kde.kword", @"kwd",
										  @"application/vnd.kde.kword", @"kwt",
										  @"application/vnd.kenameaapp", @"htke",
										  @"application/vnd.kidspiration", @"kia",
										  @"application/vnd.kinar", @"kne",
										  @"application/vnd.kinar", @"knp",
										  @"application/vnd.koan", @"skp",
										  @"application/vnd.koan", @"skd",
										  @"application/vnd.koan", @"skt",
										  @"application/vnd.koan", @"skm",
										  @"application/vnd.llamagraphics.life-balance.desktop", @"lbd",
										  @"application/vnd.llamagraphics.life-balance.exchange+xml", @"lbe",
										  @"application/vnd.lotus-1-2-3", @"123",
										  @"application/vnd.lotus-approach", @"apr",
										  @"application/vnd.lotus-freelance", @"pre",
										  @"application/vnd.lotus-notes", @"nsf",
										  @"application/vnd.lotus-organizer", @"org",
										  @"application/vnd.lotus-screencam", @"scm",
										  @"application/vnd.lotus-wordpro", @"lwp",
										  @"application/vnd.macports.portpkg", @"portpkg",
										  @"application/vnd.mcd", @"mcd",
										  @"application/vnd.medcalcdata", @"mc1",
										  @"application/vnd.mediastation.cdkey", @"cdkey",
										  @"application/vnd.mfer", @"mwf",
										  @"application/vnd.mfmp", @"mfm",
										  @"application/vnd.micrografx.flo", @"flo",
										  @"application/vnd.micrografx.igx", @"igx",
										  @"application/vnd.mif", @"mif",
										  @"application/vnd.mobius.daf", @"daf",
										  @"application/vnd.mobius.dis", @"dis",
										  @"application/vnd.mobius.mbk", @"mbk",
										  @"application/vnd.mobius.mqy", @"mqy",
										  @"application/vnd.mobius.msl", @"msl",
										  @"application/vnd.mobius.plc", @"plc",
										  @"application/vnd.mobius.txf", @"txf",
										  @"application/vnd.mophun.application", @"mpn",
										  @"application/vnd.mophun.certificate", @"mpc",
										  @"application/vnd.mozilla.xul+xml", @"xul",
										  @"application/vnd.ms-artgalry", @"cil",
										  @"application/vnd.ms-asf", @"asf",
										  @"application/vnd.ms-cab-compressed", @"cab",
										  @"application/vnd.ms-excel", @"xls",
										  @"application/vnd.ms-excel", @"xlm",
										  @"application/vnd.ms-excel", @"xla",
										  @"application/vnd.ms-excel", @"xlc",
										  @"application/vnd.ms-excel", @"xlt",
										  @"application/vnd.ms-excel", @"xlw",
										  @"application/vnd.ms-fontobject", @"eot",
										  @"application/vnd.ms-htmlhelp", @"chm",
										  @"application/vnd.ms-ims", @"ims",
										  @"application/vnd.ms-lrm", @"lrm",
										  @"application/vnd.ms-powerpoint", @"ppt",
										  @"application/vnd.ms-powerpoint", @"pps",
										  @"application/vnd.ms-powerpoint", @"pot",
										  @"application/vnd.ms-project", @"mpp",
										  @"application/vnd.ms-project", @"mpt",
										  @"application/vnd.ms-works", @"wps",
										  @"application/vnd.ms-works", @"wks",
										  @"application/vnd.ms-works", @"wcm",
										  @"application/vnd.ms-works", @"wdb",
										  @"application/vnd.ms-wpl", @"wpl",
										  @"application/vnd.ms-xpsdocument", @"xps",
										  @"application/vnd.mseq", @"mseq",
										  @"application/vnd.musician", @"mus",
										  @"application/vnd.neurolanguage.nlu", @"nlu",
										  @"application/vnd.noblenet-directory", @"nnd",
										  @"application/vnd.noblenet-sealer", @"nns",
										  @"application/vnd.noblenet-web", @"nnw",
										  @"application/vnd.nokia.n-gage.data", @"ngdat",
										  @"application/vnd.nokia.n-gage.symbian.install", @"n-gage",
										  @"application/vnd.nokia.radio-preset", @"rpst",
										  @"application/vnd.nokia.radio-presets", @"rpss",
										  @"application/vnd.novadigm.edm", @"edm",
										  @"application/vnd.novadigm.edx", @"edx",
										  @"application/vnd.novadigm.ext", @"ext",
										  @"application/vnd.oasis.opendocument.chart", @"odc",
										  @"application/vnd.oasis.opendocument.chart-template", @"otc",
										  @"application/vnd.oasis.opendocument.formula", @"odf",
										  @"application/vnd.oasis.opendocument.formula-template", @"otf",
										  @"application/vnd.oasis.opendocument.graphics", @"odg",
										  @"application/vnd.oasis.opendocument.graphics-template", @"otg",
										  @"application/vnd.oasis.opendocument.image", @"odi",
										  @"application/vnd.oasis.opendocument.image-template", @"oti",
										  @"application/vnd.oasis.opendocument.presentation", @"odp",
										  @"application/vnd.oasis.opendocument.presentation-template", @"otp",
										  @"application/vnd.oasis.opendocument.spreadsheet", @"ods",
										  @"application/vnd.oasis.opendocument.spreadsheet-template", @"ots",
										  @"application/vnd.oasis.opendocument.text", @"odt",
										  @"application/vnd.oasis.opendocument.text-master", @"otm",
										  @"application/vnd.oasis.opendocument.text-template", @"ott",
										  @"application/vnd.oasis.opendocument.text-web", @"oth",
										  @"application/vnd.olpc-sugar", @"xo",
										  @"application/vnd.oma.dd2+xml", @"dd2",
										  @"application/vnd.openofficeorg.extension", @"oxt",
										  @"application/vnd.osgi.dp", @"dp",
										  @"application/vnd.palm", @"prc",
										  @"application/vnd.palm", @"pdb",
										  @"application/vnd.palm", @"pqa",
										  @"application/vnd.palm", @"oprc",
										  @"application/vnd.pg.format", @"str",
										  @"application/vnd.pg.osasli", @"ei6",
										  @"application/vnd.picsel", @"efif",
										  @"application/vnd.pocketlearn", @"plf",
										  @"application/vnd.powerbuilder6", @"pbd",
										  @"application/vnd.previewsystems.box", @"box",
										  @"application/vnd.proteus.magazine", @"mgz",
										  @"application/vnd.publishare-delta-tree", @"qps",
										  @"application/vnd.pvi.ptid1", @"ptid",
										  @"application/vnd.quark.quarkxpress", @"qxd",
										  @"application/vnd.quark.quarkxpress", @"qxt",
										  @"application/vnd.quark.quarkxpress", @"qwd",
										  @"application/vnd.quark.quarkxpress", @"qwt",
										  @"application/vnd.quark.quarkxpress", @"qxl",
										  @"application/vnd.quark.quarkxpress", @"qxb",
										  @"application/vnd.recordare.musicxml", @"mxl",
										  @"application/vnd.rn-realmedia", @"rm",
										  @"application/vnd.seemail", @"see",
										  @"application/vnd.sema", @"sema",
										  @"application/vnd.semd", @"semd",
										  @"application/vnd.semf", @"semf",
										  @"application/vnd.shana.informed.formdata", @"ifm",
										  @"application/vnd.shana.informed.formtemplate", @"itp",
										  @"application/vnd.shana.informed.interchange", @"iif",
										  @"application/vnd.shana.informed.package", @"ipk",
										  @"application/vnd.simtech-mindmapper", @"twd",
										  @"application/vnd.simtech-mindmapper", @"twds",
										  @"application/vnd.smaf", @"mmf",
										  @"application/vnd.solent.sdkm+xml", @"sdkm",
										  @"application/vnd.solent.sdkm+xml", @"sdkd",
										  @"application/vnd.spotfire.dxp", @"dxp",
										  @"application/vnd.spotfire.sfs", @"sfs",
										  @"application/vnd.sus-calendar", @"sus",
										  @"application/vnd.sus-calendar", @"susp",
										  @"application/vnd.svd", @"svd",
										  @"application/vnd.syncml+xml", @"xsm",
										  @"application/vnd.syncml.dm+wbxml", @"bdm",
										  @"application/vnd.syncml.dm+xml", @"xdm",
										  @"application/vnd.tao.intent-module-archive", @"tao",
										  @"application/vnd.tmobile-livetv", @"tmo",
										  @"application/vnd.trid.tpt", @"tpt",
										  @"application/vnd.triscape.mxs", @"mxs",
										  @"application/vnd.trueapp", @"tra",
										  @"application/vnd.ufdl", @"ufd",
										  @"application/vnd.ufdl", @"ufdl",
										  @"application/vnd.uiq.theme", @"utz",
										  @"application/vnd.umajin", @"umj",
										  @"application/vnd.unity", @"unityweb",
										  @"application/vnd.uoml+xml", @"uoml",
										  @"application/vnd.vcx", @"vcx",
										  @"application/vnd.visio", @"vsd",
										  @"application/vnd.visio", @"vst",
										  @"application/vnd.visio", @"vss",
										  @"application/vnd.visio", @"vsw",
										  @"application/vnd.visionary", @"vis",
										  @"application/vnd.vsf", @"vsf",
										  @"application/vnd.wap.wbxml", @"wbxml",
										  @"application/vnd.wap.wmlc", @"wmlc",
										  @"application/vnd.wap.wmlscriptc", @"wmlsc",
										  @"application/vnd.webturbo", @"wtb",
										  @"application/vnd.wordperfect", @"wpd",
										  @"application/vnd.wqd", @"wqd",
										  @"application/vnd.wt.stf", @"stf",
										  @"application/vnd.xara", @"xar",
										  @"application/vnd.xfdl", @"xfdl",
										  @"application/vnd.yamaha.hv-dic", @"hvd",
										  @"application/vnd.yamaha.hv-script", @"hvs",
										  @"application/vnd.yamaha.hv-voice", @"hvp",
										  @"application/vnd.yamaha.smaf-audio", @"saf",
										  @"application/vnd.yamaha.smaf-phrase", @"spf",
										  @"application/vnd.yellowriver-custom-menu", @"cmp",
										  @"application/vnd.zzazz.deck+xml", @"zaz",
										  @"application/voicexml+xml", @"vxml",
										  @"application/winhlp", @"hlp",
										  @"application/wsdl+xml", @"wsdl",
										  @"application/wspolicy+xml", @"wspolicy",
										  @"application/x-ace-compressed", @"ace",
										  @"application/x-bcpio", @"bcpio",
										  @"application/x-bittorrent", @"torrent",
										  @"application/x-bzip", @"bz",
										  @"application/x-bzip2", @"bz2",
										  @"application/x-bzip2", @"boz",
										  @"application/x-cdlink", @"vcd",
										  @"application/x-chat", @"chat",
										  @"application/x-chess-pgn", @"pgn",
										  @"application/x-cpio", @"cpio",
										  @"application/x-csh", @"csh",
										  @"application/x-director", @"dcr",
										  @"application/x-director", @"dir",
										  @"application/x-director", @"dxr",
										  @"application/x-director", @"fgd",
										  @"application/x-dvi", @"dvi",
										  @"application/x-futuresplash", @"spl",
										  @"application/x-gtar", @"gtar",
										  @"application/x-hdf", @"hdf",
										  @"application/x-java-jnlp-file", @"jnlp",
										  @"application/x-latex", @"latex",
										  @"application/x-ms-wmd", @"wmd",
										  @"application/x-ms-wmz", @"wmz",
										  @"application/x-msaccess", @"mdb",
										  @"application/x-msbinder", @"obd",
										  @"application/x-mscardfile", @"crd",
										  @"application/x-msclip", @"clp",
										  @"application/x-msdownload", @"exe",
										  @"application/x-msdownload", @"dll",
										  @"application/x-msdownload", @"com",
										  @"application/x-msdownload", @"bat",
										  @"application/x-msdownload", @"msi",
										  @"application/x-msmediaview", @"mvb",
										  @"application/x-msmediaview", @"m13",
										  @"application/x-msmediaview", @"m14",
										  @"application/x-msmetafile", @"wmf",
										  @"application/x-msmoney", @"mny",
										  @"application/x-mspublisher", @"pub",
										  @"application/x-msschedule", @"scd",
										  @"application/x-msterminal", @"trm",
										  @"application/x-mswrite", @"wri",
										  @"application/x-netcdf", @"nc",
										  @"application/x-netcdf", @"cdf",
										  @"application/x-pkcs12", @"p12",
										  @"application/x-pkcs12", @"pfx",
										  @"application/x-pkcs7-certificates", @"p7b",
										  @"application/x-pkcs7-certificates", @"spc",
										  @"application/x-pkcs7-certreqresp", @"p7r",
										  @"application/x-rar-compressed", @"rar",
										  @"application/x-sh", @"sh",
										  @"application/x-shar", @"shar",
										  @"application/x-shockwave-flash", @"swf",
										  @"application/x-stuffit", @"sit",
										  @"application/x-stuffitx", @"sitx",
										  @"application/x-sv4cpio", @"sv4cpio",
										  @"application/x-sv4crc", @"sv4crc",
										  @"application/x-tar", @"tar",
										  @"application/x-tcl", @"tcl",
										  @"application/x-tex", @"tex",
										  @"application/x-texinfo", @"texinfo",
										  @"application/x-texinfo", @"texi",
										  @"application/x-ustar", @"ustar",
										  @"application/x-wais-source", @"src",
										  @"application/x-x509-ca-cert", @"der",
										  @"application/x-x509-ca-cert", @"crt",
										  @"application/xenc+xml", @"xenc",
										  @"application/xhtml+xml", @"xhtml",
										  @"application/xhtml+xml", @"xht",
										  @"application/xml", @"xml",
										  @"application/xml", @"xsl",
										  @"application/xml-dtd", @"dtd",
										  @"application/xop+xml", @"xop",
										  @"application/xslt+xml", @"xslt",
										  @"application/xspf+xml", @"xspf",
										  @"application/xv+xml", @"mxml",
										  @"application/xv+xml", @"xhvml",
										  @"application/xv+xml", @"xvml",
										  @"application/xv+xml", @"xvm",
										  @"application/zip", @"zip",
										  @"audio/basic", @"au",
										  @"audio/basic", @"snd",
										  @"audio/midi", @"mid",
										  @"audio/midi", @"midi",
										  @"audio/midi", @"kar",
										  @"audio/midi", @"rmi",
										  @"audio/mp4", @"mp4a",
										  @"audio/x-m4a", @"m4a",
										  @"audio/x-m4p", @"m4p",
										  @"audio/mpeg", @"mpga",
										  @"audio/mpeg", @"mp2",
										  @"audio/mpeg", @"mp2a",
										  @"audio/mpeg", @"mp3",
										  @"audio/mpeg", @"m2a",
										  @"audio/mpeg", @"m3a",
										  @"audio/vnd.digital-winds", @"eol",
										  @"audio/vnd.lucent.voice", @"lvp",
										  @"audio/vnd.nuera.ecelp4800", @"ecelp4800",
										  @"audio/vnd.nuera.ecelp7470", @"ecelp7470",
										  @"audio/vnd.nuera.ecelp9600", @"ecelp9600",
										  @"audio/wav", @"wav",
										  @"audio/x-aiff", @"aif",
										  @"audio/x-aiff", @"aiff",
										  @"audio/x-aiff", @"aifc",
										  @"audio/x-mpegurl", @"m3u",
										  @"audio/x-ms-wax", @"wax",
										  @"audio/x-ms-wma", @"wma",
										  @"audio/x-pn-realaudio", @"ram",
										  @"audio/x-pn-realaudio", @"ra",
										  @"audio/x-pn-realaudio-plugin", @"rmp",
										  @"audio/x-wav", @"wav",
										  @"chemical/x-cdx", @"cdx",
										  @"chemical/x-cif", @"cif",
										  @"chemical/x-cmdf", @"cmdf",
										  @"chemical/x-cml", @"cml",
										  @"chemical/x-csml", @"csml",
										  @"chemical/x-pdb", @"pdb",
										  @"chemical/x-xyz", @"xyz",
										  @"image/bmp", @"bmp",
										  @"image/cgm", @"cgm",
										  @"image/g3fax", @"g3",
										  @"image/gif", @"gif",
										  @"image/ief", @"ief",
										  @"image/jp2", @"jp2",
										  @"image/jpeg", @"jpeg",
										  @"image/jpeg", @"jpg",
										  @"image/jpeg", @"jpe",
										  @"image/pict", @"pict",
										  @"image/pict", @"pic",
										  @"image/pict", @"pct",
										  @"image/png", @"png",
										  @"image/prs.btif", @"btif",
										  @"image/svg+xml", @"svg",
										  @"image/svg+xml", @"svgz",
										  @"image/tiff", @"tiff",
										  @"image/tiff", @"tif",
										  @"image/vnd.adobe.photoshop", @"psd",
										  @"image/vnd.djvu", @"djvu",
										  @"image/vnd.djvu", @"djv",
										  @"image/vnd.dwg", @"dwg",
										  @"image/vnd.dxf", @"dxf",
										  @"image/vnd.fastbidsheet", @"fbs",
										  @"image/vnd.fpx", @"fpx",
										  @"image/vnd.fst", @"fst",
										  @"image/vnd.fujixerox.edmics-mmr", @"mmr",
										  @"image/vnd.fujixerox.edmics-rlc", @"rlc",
										  @"image/vnd.microsoft.icon", @"ico",
										  @"image/vnd.ms-modi", @"mdi",
										  @"image/vnd.net-fpx", @"npx",
										  @"image/vnd.wap.wbmp", @"wbmp",
										  @"image/vnd.xiff", @"xif",
										  @"image/x-cmu-raster", @"ras",
										  @"image/x-cmx", @"cmx",
										  @"image/x-macpaint", @"pntg",
										  @"image/x-macpaint", @"pnt",
										  @"image/x-macpaint", @"mac",
										  @"image/x-pcx", @"pcx",
										  @"image/x-pict", @"pic",
										  @"image/x-pict", @"pct",
										  @"image/x-portable-anymap", @"pnm",
										  @"image/x-portable-bitmap", @"pbm",
										  @"image/x-portable-graymap", @"pgm",
										  @"image/x-portable-pixmap", @"ppm",
										  @"image/x-quicktime", @"qtif",
										  @"image/x-quicktime", @"qti",
										  @"image/x-rgb", @"rgb",
										  @"image/x-xbitmap", @"xbm",
										  @"image/x-xpixmap", @"xpm",
										  @"image/x-xwindowdump", @"xwd",
										  @"message/rfc822", @"eml",
										  @"message/rfc822", @"mime",
										  @"model/iges", @"igs",
										  @"model/iges", @"iges",
										  @"model/mesh", @"msh",
										  @"model/mesh", @"mesh",
										  @"model/mesh", @"silo",
										  @"model/vnd.dwf", @"dwf",
										  @"model/vnd.gdl", @"gdl",
										  @"model/vnd.gtw", @"gtw",
										  @"model/vnd.mts", @"mts",
										  @"model/vnd.vtu", @"vtu",
										  @"model/vrml", @"wrl",
										  @"model/vrml", @"vrml",
										  @"text/calendar", @"ics",
										  @"text/calendar", @"ifb",
										  @"text/css", @"css",
										  @"text/csv", @"csv",
										  @"text/html", @"html",
										  @"text/html", @"htm",
										  @"text/plain", @"txt",
										  @"text/plain", @"text",
										  @"text/plain", @"conf",
										  @"text/plain", @"def",
										  @"text/plain", @"list",
										  @"text/plain", @"log",
										  @"text/plain", @"in",
										  @"text/prs.lines.tag", @"dsc",
										  @"text/richtext", @"rtx",
										  @"text/sgml", @"sgml",
										  @"text/sgml", @"sgm",
										  @"text/tab-separated-values", @"tsv",
										  @"text/troff", @"t",
										  @"text/troff", @"tr",
										  @"text/troff", @"roff",
										  @"text/troff", @"man",
										  @"text/troff", @"me",
										  @"text/troff", @"ms",
										  @"text/uri-list", @"uri",
										  @"text/uri-list", @"uris",
										  @"text/uri-list", @"urls",
										  @"text/vnd.fly", @"fly",
										  @"text/vnd.fmi.flexstor", @"flx",
										  @"text/vnd.in3d.3dml", @"3dml",
										  @"text/vnd.in3d.spot", @"spot",
										  @"text/vnd.sun.j2me.app-descriptor", @"jad",
										  @"text/vnd.wap.wml", @"wml",
										  @"text/vnd.wap.wmlscript", @"wmls",
										  @"text/x-asm", @"s",
										  @"text/x-asm", @"asm",
										  @"text/x-c", @"c",
										  @"text/x-c", @"cc",
										  @"text/x-c", @"cxx",
										  @"text/x-c", @"cpp",
										  @"text/x-c", @"h",
										  @"text/x-c", @"hh",
										  @"text/x-c", @"dic",
										  @"text/x-fortran", @"f",
										  @"text/x-fortran", @"for",
										  @"text/x-fortran", @"f77",
										  @"text/x-fortran", @"f90",
										  @"text/x-pascal", @"p",
										  @"text/x-pascal", @"pas",
										  @"text/x-java-source", @"java",
										  @"text/x-setext", @"etx",
										  @"text/x-uuencode", @"uu",
										  @"text/x-vcalendar", @"vcs",
										  @"text/x-vcard", @"vcf",
										  @"video/3gpp", @"3gp",
										  @"video/3gpp2", @"3g2",
										  @"video/h261", @"h261",
										  @"video/h263", @"h263",
										  @"video/h264", @"h264",
										  @"video/jpeg", @"jpgv",
										  @"video/jpm", @"jpm",
										  @"video/jpm", @"jpgm",
										  @"video/mj2", @"mj2",
										  @"video/mj2", @"mjp2",
										  @"video/mp4", @"mp4",
										  @"video/mp4", @"mp4v",
										  @"video/mp4", @"mpg4",
										  @"video/mp4", @"m4v",
										  @"video/mpeg", @"mpeg",
										  @"video/mpeg", @"mpg",
										  @"video/mpeg", @"mpe",
										  @"video/mpeg", @"m1v",
										  @"video/mpeg", @"m2v",
										  @"video/quicktime", @"qt",
										  @"video/quicktime", @"mov",
										  @"video/vnd.fvt", @"fvt",
										  @"video/vnd.mpegurl", @"mxu",
										  @"video/vnd.mpegurl", @"m4u",
										  @"video/vnd.vivo", @"viv",
										  @"video/x-dv", @"dv",
										  @"video/x-dv", @"dif",
										  @"video/x-fli", @"fli",
										  @"video/x-ms-asf", @"asf",
										  @"video/x-ms-asf", @"asx",
										  @"video/x-ms-wm", @"wm",
										  @"video/x-ms-wmv", @"wmv",
										  @"video/x-ms-wmx", @"wmx",
										  @"video/x-ms-wvx", @"wvx",
										  @"video/x-msvideo", @"avi",
										  @"video/x-sgi-movie", @"movie",
										  @"x-conference/x-cooltalk", @"ice",
										   nil];
	}
	
	NSString *filePath = [[directoryPath stringByAppendingPathComponent:[theRequest relativePath]] stringByStandardizingPath];
	if (![filePath hasPrefix:directoryPath])
	{
		[theRequest setResponseString:@"<h1>403 Forbidden</h1><p>Directory exists above document root.</p>"];
		[theRequest setResponseContentType:@"text/html"];
		[theRequest setResponseStatusCode:403];
		[theRequest sendResponse];
	}
	BOOL isDir;
	if ([[NSFileManager defaultManager] fileExistsAtPath:filePath isDirectory:&isDir])
	{
		if (!isDir)
		{
			NSData *r = [NSData dataWithContentsOfFile:filePath];
			[theRequest setResponseBody:r];
			NSString *typeLookup = [[filePath pathExtension] lowercaseString];
			if ([supportedTypes containsKey:typeLookup])
				[theRequest setResponseContentType:[supportedTypes valueForKey:typeLookup]];
			else
				[theRequest setResponseContentType:@"text/plain"];
		}
		else
		{
			if (allowDirectoryListing)
			{
				NSMutableString *str = [NSMutableString stringWithFormat:@"<h1>Directory Listing: %@</h1><ul>", [filePath lastPathComponent]];
				NSArray *files = [[NSFileManager defaultManager] directoryContentsAtPath:filePath];
				NSEnumerator *e = [files objectEnumerator];
				NSString *file;
				while (file = [e nextObject])
					[str appendFormat:@"<li><a href=\"%@\">%@</a></li>", [[theRequest fullPath] stringByAppendingPathComponent:file], file];
				[str appendString:@"</ul>"];
				[theRequest setResponseString:str];
				[theRequest setResponseContentType:@"text/html"];
			}
			else
			{
				[theRequest setResponseString:@"<h1>403 Forbidden</h1><p>Directory listing is not allowed.</p>"];
				[theRequest setResponseContentType:@"text/html"];
				[theRequest setResponseStatusCode:403];
			}
		}
	}
	else
	{
		[theRequest setResponseString:@"<h1>404 File Not Found</h1>"];
		[theRequest setResponseContentType:@"text/html"];
		[theRequest setResponseStatusCode:404];
	}
	
	[theRequest sendResponse];
}

@end
